import {db,now,uid,digest,hash,verify,current,safeUser,log,requestIp,trustedOrigin} from '@/lib/hub-server';
export const runtime='nodejs';
export const dynamic='force-dynamic';
const json=(v:any,status=200,headers={})=>Response.json(v,{status,headers:{'Cache-Control':'no-store',...headers}});
export async function GET(req:Request){try{const u=await current(req);if(!u)return json({user:null});const d=db();const admin=u.role==='admin';const selected=admin?new URL(req.url).searchParams.get('student'):null;const gems=(await d.prepare('SELECT * FROM gem_links ORDER BY sequence').all()).results;const p=(await d.prepare(admin?'SELECT * FROM student_progress':'SELECT * FROM student_progress WHERE user_id=?').bind(...(admin?[]:[u.id])).all()).results;const board=await d.prepare("SELECT value FROM settings WHERE key='board'").first();const students=admin?(await d.prepare("SELECT id,username,full_name,role,active,first_login,last_login,login_count,(SELECT MAX(heartbeat) FROM sessions WHERE user_id=users.id AND expires_at>?) AS heartbeat,(SELECT MAX(created_at) FROM activity_logs WHERE user_id=users.id) AS last_activity FROM users WHERE role='student' ORDER BY username").bind(now()).all()).results:[];const acts=(await d.prepare('SELECT a.*,u.username,u.full_name,g.title FROM activity_logs a JOIN users u ON a.user_id=u.id LEFT JOIN gem_links g ON g.id=a.gem_id '+(selected||!admin?'WHERE a.user_id=? ':'')+'ORDER BY a.created_at DESC'+(selected?'':' LIMIT 500')).bind(...(selected?[selected]:admin?[]:[u.id])).all()).results;const logins=admin?(await d.prepare("SELECT substr(login_at,1,10) AS day,COUNT(*)::int AS count FROM login_logs WHERE login_at>=? GROUP BY day ORDER BY day").bind(new Date(Date.now()-30*86400000).toISOString()).all()).results:[];const boards=board?.value==='1'?(await d.prepare("SELECT u.id,u.full_name,COUNT(CASE WHEN p.status='completed' THEN 1 END)::int completed FROM users u LEFT JOIN student_progress p ON p.user_id=u.id WHERE u.role='student' AND u.active=1 GROUP BY u.id ORDER BY u.username").all()).results:[];return json({user:safeUser(u),gems,progress:p,students,activities:acts,logins,board:board?.value==='1',boards});}catch(e){console.error('Hub operation failed', e instanceof Error ? e.name : 'Error');return json({error:'โหลดข้อมูลไม่สำเร็จ กรุณาลองใหม่'},503);}}
export async function POST(req:Request){try{if(!trustedOrigin(req))return json({error:'คำขอไม่ถูกต้อง'},403);if(Number(req.headers.get('content-length')||0)>20000)return json({error:'ข้อมูลมีขนาดใหญ่เกินไป'},413);const text=await req.text();if(text.length>20000)return json({error:'ข้อมูลมีขนาดใหญ่เกินไป'},413);const b=JSON.parse(text);const d=db();if(b.action==='login'){if(typeof b.username!=='string'||typeof b.password!=='string'||b.password.length>200)return json({error:'ข้อมูลไม่ถูกต้อง'},400);const key=await digest(requestIp(req)+':'+b.username.trim().toLowerCase());const a=await d.prepare('SELECT * FROM login_attempts WHERE key=?').bind(key).first();if(a&&a.expires_at>now()&&a.count>=10)return json({error:'ลองหลายครั้งเกินไป กรุณารอ 15 นาที'},429);const u=await d.prepare('SELECT * FROM users WHERE username=? AND active=1').bind(b.username.trim()).first();const ok=await verify(b.password,u?.password_hash||'dummy:0000000000000000000000000000000000000000000000000000000000000000');if(!u||!ok){await d.prepare('INSERT INTO login_attempts(key,count,expires_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN login_attempts.expires_at>? THEN login_attempts.count+1 ELSE 1 END,expires_at=excluded.expires_at').bind(key,new Date(Date.now()+900000).toISOString(),now()).run();return json({error:'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง'},401);}const t=uid()+uid(),date=now();await d.batch([d.prepare('DELETE FROM login_attempts WHERE key=?').bind(key),d.prepare('INSERT INTO sessions(token,user_id,expires_at,heartbeat) VALUES(?,?,?,?)').bind(await digest(t),u.id,new Date(Date.now()+8*3600000).toISOString(),date),d.prepare('UPDATE users SET first_login=COALESCE(first_login,?),last_login=?,login_count=login_count+1 WHERE id=?').bind(date,date,u.id),d.prepare('INSERT INTO login_logs(id,user_id,login_at,ip_address,user_agent) VALUES(?,?,?,?,?)').bind(uid(),u.id,date,requestIp(req),req.headers.get('user-agent')),log(u.id,'login')]);return json({ok:true,role:u.role},200,{'Set-Cookie':`gem_session=${t}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=28800`});}
const u=await current(req);if(!u)return json({error:'กรุณาเข้าสู่ระบบ'},401);
if(b.action==='logout'){const t=req.headers.get('cookie')?.match(/(?:^|; )gem_session=([^;]+)/)?.[1]||'';await d.batch([d.prepare('DELETE FROM sessions WHERE token=?').bind(await digest(t)),log(u.id,'logout')]);return json({ok:true},200,{'Set-Cookie':'gem_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0'});}
if(b.action==='heartbeat'){const t=req.headers.get('cookie')?.match(/(?:^|; )gem_session=([^;]+)/)?.[1]||'';await d.prepare('UPDATE sessions SET heartbeat=? WHERE token=?').bind(now(),await digest(t)).run();return json({ok:true});}
if(b.action==='password'){if(typeof b.password!=='string'||b.password.length<10||b.password.length>200)return json({error:'รหัสผ่านต้องยาว 10–200 ตัวอักษร'},400);if(!await verify(b.oldPassword||'',u.password_hash))return json({error:'รหัสผ่านเดิมไม่ถูกต้อง'},400);await d.batch([d.prepare('UPDATE users SET password_hash=? WHERE id=?').bind(await hash(b.password),u.id),d.prepare('DELETE FROM sessions WHERE user_id=?').bind(u.id),log(u.id,'password')]);return json({ok:true,relogin:true});}
if(b.action==='open'||b.action==='complete'){if(u.role!=='student')return json({error:'สำหรับนักเรียนเท่านั้น'},403);const g=await d.prepare('SELECT * FROM gem_links WHERE id=? AND active=1').bind(Number(b.gemId)).first();if(!g)return json({error:'Gem นี้ปิดใช้งาน'},400);const date=now();const stmt=b.action==='open'?d.prepare("INSERT INTO student_progress(user_id,gem_id,status,first_opened_at,last_opened_at,open_count) VALUES(?,?,'in_progress',?,?,1) ON CONFLICT(user_id,gem_id) DO UPDATE SET status=CASE WHEN student_progress.status='completed' THEN student_progress.status ELSE 'in_progress' END,first_opened_at=COALESCE(student_progress.first_opened_at,excluded.first_opened_at),last_opened_at=excluded.last_opened_at,open_count=student_progress.open_count+1").bind(u.id,g.id,date,date):d.prepare("INSERT INTO student_progress(user_id,gem_id,status,completed_at) VALUES(?,?,'completed',?) ON CONFLICT(user_id,gem_id) DO UPDATE SET status='completed',completed_at=COALESCE(student_progress.completed_at,excluded.completed_at)").bind(u.id,g.id,date);await d.batch([stmt,log(u.id,b.action,g.id)]);return json({ok:true,url:g.url});}
if(u.role!=='admin')return json({error:'ไม่มีสิทธิ์เข้าถึง'},403);
if(b.action==='board'){await d.prepare("UPDATE settings SET value=? WHERE key='board'").bind(b.value?'1':'0').run();}
else if(b.action==='student'){if(typeof b.full_name!=='string'||!b.full_name.trim()||b.full_name.length>150)return json({error:'กรุณาระบุชื่อ'},400);if(b.id){await d.batch([d.prepare("UPDATE users SET full_name=?,active=? WHERE id=? AND role='student'").bind(b.full_name,b.active?1:0,b.id),...(!b.active?[d.prepare('DELETE FROM sessions WHERE user_id=?').bind(b.id)]:[])]);}else{if(!/^[a-zA-Z0-9_-]{3,40}$/.test(b.username)||!b.password||b.password.length<10)return json({error:'ชื่อผู้ใช้ 3–40 ตัวอักษรอังกฤษ และรหัสผ่านอย่างน้อย 10 ตัว'},400);await d.prepare('INSERT INTO users(id,username,password_hash,full_name,role,created_at) VALUES(?,?,?,?,?,?)').bind(uid(),b.username,await hash(b.password),b.full_name,'student',now()).run();}}
else if(b.action==='reset'){if(typeof b.password!=='string'||b.password.length<10||b.password.length>200)return json({error:'รหัสผ่านต้องยาว 10–200 ตัวอักษร'},400);const target=await d.prepare("SELECT id FROM users WHERE id=? AND role='student'").bind(b.id).first();if(!target)return json({error:'ไม่พบบัญชี'},404);await d.batch([d.prepare('UPDATE users SET password_hash=? WHERE id=?').bind(await hash(b.password),b.id),d.prepare('DELETE FROM sessions WHERE user_id=?').bind(b.id),log(b.id,'reset')]);}
else if(b.action==='gem'){const url=new URL(b.url);if(url.protocol!=='https:'||url.hostname!=='gemini.google.com')return json({error:'ใช้ลิงก์ https://gemini.google.com เท่านั้น'},400);if(!b.title?.trim()||!b.description?.trim()||!Number.isInteger(Number(b.sequence))||Number(b.sequence)<1)return json({error:'กรอกข้อมูล Gem ให้ครบ'},400);await d.prepare('UPDATE gem_links SET title=?,description=?,url=?,sequence=?,active=? WHERE id=?').bind(b.title,b.description,b.url,Number(b.sequence),b.active?1:0,b.id).run();}
else return json({error:'ไม่พบคำสั่ง'},400);return json({ok:true});}catch(e){console.error('Hub operation failed', e instanceof Error ? e.name : 'Error');return json({error:'บันทึกไม่สำเร็จ ตรวจสอบข้อมูลหรือชื่อผู้ใช้ซ้ำ แล้วลองใหม่'},500);}}
